accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('profile/', views.Profile.as_view(), name='profile'),
    path('password/', views.ChangePassword.as_view(), name='change-password'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    # path('activate/account/<uuid:activation_key>/', views.Activate.as_view(), name='activate'),
    path('activate/<slug:uidb64>/<slug:token>/', views.activate, name='activate')
]

api/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from api.views import RateViewSet, BankViewSet, RateChoicesView, ContactUsViewSet
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


router = DefaultRouter()
router.register(r'rates', RateViewSet, basename='rate')
router.register(r'banks', BankViewSet, basename='bank')
router.register(r'contacts', ContactUsViewSet, basename='contact')
urlpatterns = [
    path('choices/currency/types/', RateChoicesView.as_view(), name='choices-currency-types'),
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]
urlpatterns += router.urls

currency/urls.py
from django.conf.urls import url

import currency.settings
from currency_app.views import index_page
from django.contrib import admin
from django.urls import path, include
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', index_page, name='index'),
    path('currency/', include('currency_app.urls')),
    path('accounts/', include('accounts.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    url('^', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.v1.urls')),
    # path('api/rates/', RateList.as_view()),
    # path('api/rates/<int:pk>', RateDetails.as_view()),
    # path('api/banks/', BankList.as_view()),
]

if currency.settings.DEBUG:
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)), )

currency_app/urls.py
from django.urls import path
from currency_app.views import (
                                Ratelist,
                                rate_edit,
                                rate_delete_single,
                                BankList,
                                BankCreate,
                                BankReadSingle,
                                BankUpdateSingle,
                                BankDeleteSingle,
                                contact_us_list,
                                contact_us_delete,
                                ContactUsCreate,
                                RateListApi,
                                )

app_name = 'currency_app'

urlpatterns = [
    path('rate/list/', Ratelist.as_view(), name='rate-list'),
    path('rate/edit/<int:pk>/<m>/<s>/<b>/<src>/', rate_edit, name='rate-edit'),
    path('rate/delete_single/<int:pk>/', rate_delete_single, name='rate_delete_single'),
    path('bank/list/', BankList.as_view(), name='bank-list'),
    path('bank/create/', BankCreate.as_view(), name='bank-create'),
    path('bank/read_single/<int:pk>/', BankReadSingle.as_view(), name='bank-read-single'),
    path('bank/edit/<int:pk>/', BankUpdateSingle.as_view(), name='bank-update-single'),
    path('bank/delete_single/<int:pk>/', BankDeleteSingle.as_view(), name='bank-delete-single'),
    path('сontact_us/create/', ContactUsCreate.as_view(), name='contact_us_create'),
    path('сontact_us/list/', contact_us_list, name='contact_us_list'),
    path('сontact_us/delete_single/<int:pk>/', contact_us_delete, name='contact_us_delete'),
    path('self_made_api/rates/', RateListApi.as_view(), name='api-rates'),
]

currency_app/models.py
from django.db import models
from currency_app import choices


class Bank(models.Model):
    name = models.CharField(max_length=64)
    code_name = models.CharField(max_length=64, unique=True)
    url = models.URLField()
    origin_url = models.URLField()


class Rate(models.Model):
    moneytype = models.PositiveSmallIntegerField(choices=choices.RATE_TYPE_CHOICES)
    sale = models.DecimalField(max_digits=5, decimal_places=2)
    buy = models.DecimalField(max_digits=5, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    bank = models.ForeignKey(
        Bank,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f'Rate id: {self.id}'


class ContactUs(models.Model):
    email_from = models.EmailField(max_length=254)
    subject = models.CharField(max_length=255)
    message = models.CharField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)


class Analytics(models.Model):
    path = models.CharField(max_length=255)
    counter = models.PositiveBigIntegerField()
    request_method = models.PositiveSmallIntegerField(choices=choices.REQUEST_METHOD_CHOICES)
    status_code = models.CharField(max_length=3)

    class Meta:
        unique_together = [
            ['path', 'request_method']
        ]

currency_app/forms.py
from django import forms
from currency_app.models import Bank, Rate, ContactUs


class BankForm(forms.ModelForm):
    class Meta:
        model = Bank
        fields = (
            'name',
            'url',
            'origin_url',
        )


class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        fields = (
            'moneytype',
            'sale',
            'buy',
            'bank',
        )


class ContactUsCreateForm(forms.ModelForm):
    class Meta:
        model = ContactUs
        fields = (
            'email_from',
            'subject',
            'message',
        )

    #                               Do when any View is called anywhere
    # def save(self, commit =True):
    #     print('here\n'*10)
    #     return super().save(commit)

currency_app/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from currency_app.models import Rate, Bank, ContactUs
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView, View
from currency_app.forms import BankForm
from currency_app.tasks import send_mail_in_bckg
from currency_app.filters import RateFilter
from django_filters.views import FilterView


def handler404(request, exception, template_name="index.html"):
    response = render(template_name)
    response.status_code = 404
    return response


def index_page(request):
    return render(request, 'index.html')


class Ratelist(FilterView):
    model = Rate
    fields = (
        'moneytype',
        'sale',
        'buy',
        'bank',
    )
    template_name = 'rate_list.html'
    queryset = Rate.objects.all().select_related('bank')
    success_url = reverse_lazy('rate-list')
    paginate_by = 50
    filterset_class = RateFilter


def rate_edit(request, pk, m, s, b, src):
    instance = get_object_or_404(Rate, pk=pk) # noqa
    rate = Rate.objects.get(id=pk)
    rate.moneytype = m
    rate.sale = s
    rate.buy = b
    bank = Bank.objects.get(name=src)
    rate.bank = bank
    rate.save()
    # return HttpResponseRedirect(reverse('currency_app:rate-list'))
    return redirect('currency_app:rate-list')


def rate_delete_single(request, pk):
    Rate.objects.filter(pk=pk).delete()
    # return HttpResponseRedirect(reverse('currency_app:rate-list'))
    return redirect('currency_app:rate-list')


class BankList(ListView):
    model = Bank
    fields = (
        'name',
        'url',
    )
    template_name = 'bank_list.html'
    success_url = reverse_lazy('currency_app:bank-list')


class BankCreate(CreateView):
    model = Bank
    fields = (
        'name',
        'url',
    )
    template_name = 'bank_create.html'

    success_url = reverse_lazy('currency_app:bank-list')


class BankReadSingle(DetailView):
    model = Bank
    template_name = 'bank_read_single.html'
    success_url = reverse_lazy('currency_app:bank-list')


class BankUpdateSingle(UpdateView):
    queryset = Bank.objects.all()
    template_name = 'bank_update_single.html'
    success_url = reverse_lazy('currency_app:bank-list')
    form_class = BankForm


class BankDeleteSingle(DeleteView):
    model = Bank
    queryset = Bank.objects.all()
    template_name = 'bank_delete_single.html'
    success_url = reverse_lazy('currency_app:bank-list')


class ContactUsCreate(CreateView):
    model = ContactUs
    fields = (
        'email_from',
        'subject',
        'message',
    )
    template_name = 'contact_us_create.html'
    success_url = reverse_lazy('index')
    #                               Called only when this view is called

    def form_valid(self, form):
        data = form.cleaned_data
        send_mail_in_bckg.delay(data['subject'], data['email_from'])
        return super().form_valid(form)


def contact_us_list(request):
    queryset = ContactUs.objects.all()
    context = {
        'data': queryset,
    }
    return render(request, 'contact_us_list.html', context=context)


def contact_us_delete(request, pk):
    ContactUs.objects.filter(pk=pk).delete()
    return redirect('currency_app:contact_us_list')


class RateListApi(View):
    def get(self, request):
        rates = Rate.objects.all()
        results = []
        for rate in rates:
            results.append({
                'id': rate.id,
                'sale': float(rate.sale),
                'buy': float(rate.buy),
                'bank': rate.bank_id,
            })
        import json
        # print(results)
        return HttpResponse(json.dumps(results), content_type='application/json')

currency_app/templates/bank_delete_single.html
{% extends 'template.html' %}
{% block body_content %}
    <form method="post">{% csrf_token %}
        <p>
        <div class="container">
            <div class="col-md-12 text-center">
                <a href="{% url 'currency_app:bank-list' %}" class="button">Back</a>
                <button type="submit" class="btn btn-warning">Delete?</button>
            </div>
        </div>
    </form>
{% endblock body_content %}
</body>
</html>

currency_app/templates/bank_list.html
{% extends 'template.html' %}
{% block body_content %}
    {% load static %}
    <div class="row justify-content-center">
        <div class="col-auto">
            <table class="table text-center table-responsive">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Bank</th>
                    <th scope="col">Url origin</th>
                    <th scope="col">Url</th>
                    {% if request.user.id == 1 %}
                        <th scope="col">View</th>
                        <th scope="col">Edit</th>
                        <th scope="col">Delete</th>
                    {% endif %}
                </tr>
                </thead>
                <tbody>
                {% for ls_element in object_list %}
                    <tr>
                        <td class="align-middle">
                            {% if ls_element.name == "Vkurse" %}
                                <img class="pic" width="50" src="{% static 'vkurse.jpg' %}">
                            {% elif ls_element.name == "PrivatBank" %}
                                <img class="pic" width="50" src="{% static 'privatbank.jpg' %}">
                            {% elif ls_element.name == "Monobank" %}
                                <img class="pic" width="50" src="{% static 'monobank.png' %}">
                            {% elif ls_element.name == "Abank" %}
                                <img class="pic" width="50" src="{% static 'abank.png' %}">
                            {% elif ls_element.name == "Kredobank" %}
                                <img class="pic" width="50" src="{% static 'kredobank.png' %}">
                            {% elif ls_element.name == "Pivdenniy" %}
                                <img class="pic" width="50" src="{% static 'pivd.png' %}">
                            {% else %}
                                <img class="pic" width="50" src="{% static 'no_image.png' %}">
                            {% endif %}
                        </td>
                        <td class="text-truncate align-middle">
                            {{ ls_element.name }}
                        </td>
                        <td class="text-truncate align-middle col-md-2">
                            <a href="{{ ls_element.origin_url }}" target="blank">{{ ls_element.origin_url }}</a>
                        </td>
                        <td class="text-truncate align-middle col-md-2">
                            <a href="{{ ls_element.url }}" target="blank">{{ ls_element.url }}</a>
                        </td>
                        {% if request.user.is_superuser %}
                            <td class="align-middle">
                                <button type="button" class="btn btn-warning"
                                        onclick='location.href="{% url 'currency_app:bank-read-single' ls_element.id %}"'>
                                    <i class="fas fa-eye"></i></button>
                            </td>
                            <td class="align-middle">
                                <button type="button" class="btn btn-primary"
                                        onclick='location.href="{% url 'currency_app:bank-update-single' ls_element.id %}"'>
                                    <i class="fas fa-pencil-alt"></i></button>
                            </td>
                            <td class="align-middle">
                                <button type="button" class="btn btn-danger"
                                        onclick='location.href="{% url 'currency_app:bank-delete-single' ls_element.id %}"'>
                                    <i class="fas fa-trash-alt"></i></button>
                            </td>
                            </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
        </div>
    </div>
    </table>
    {% if request.user.is_superuser %}
        <button type="button" class="btn btn-success" onclick='location.href="{% url 'currency_app:bank-create' %}"'><i
                class="fas fa-plus-circle"></i></button>
    {% endif %}
    <br>
    <br>
    <span class="glyphicon glyphicon-name"></span>
    <!-- Modal -->
    <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalbody">
                </div>
            </div>
        </div>
    </div>
    </body>
    </html>
    <script type="text/javascript">
        window.onload = function () {
            document.getElementById('footer_body').style.display = 'none';
        };
        document.getElementById("banklist").classList.add("active");
        document.title = "Bank list";
        let ids = []
        let names = []
        let urls = []
        {% for ls_element in object_list %}
            ids.push('{{ls_element.id}}')
            names.push('{{ls_element.name}}')
            urls.push('{{ls_element.url}}')
        {% endfor%}

        $('.modal').on('shown.bs.modal', function (e) {
            var action = $(e.relatedTarget).data('action');
            if (action == 'view') {
                document.getElementById('ModalLabel').innerHTML = 'View'
                var id = $(e.relatedTarget).data('id');
                for (var i = 0; i < ids.length; i++) {
                    if (ids[i] == id) {
                        id = i
                    }
                }
                $("#modalbody").append('<h5 class="card-title">' + names[id] + '</h5>' +
                    '<p class="card-text"></p>' +
                    '<a href="' + urls[id] + '" class="card-link text-truncate">' + urls[id] + '</a>' +
                    '<div class="modal-footer d-block">' +
                    '<button type="button" class="btn btn-secondary float-start" data-dismiss="modal">Close</button>' +
                    '</div>');
            } else if (action == 'update') {
                document.getElementById('ModalLabel').innerHTML = 'Update'
                var id = $(e.relatedTarget).data('id');
                var original_id = id
                for (var i = 0; i < ids.length; i++) {
                    if (ids[i] == id) {
                        id = i
                    }
                }
                $('#modalbody').append('<form id="form_upd" onsubmit="return update()">' +
                    '<div class="mb-3">' +
                    '<label id="data_id">' + original_id + '</label><p>' +
                    '<label class="form-label">Bank Name</label>' +
                    '<input type="text" maxlength="255" class="form-control" id="bname" name="bname" required value="' + names[id] + '"/>' +
                    '</div>' +
                    '<div class="mb-3">' +
                    '<label class="form-label">Link</label>' +
                    '<input type="text" maxlength="255" class="form-control" id="blink" name="subject" required value="' + urls[id] + '"/>' +
                    '</div>' +
                    '<div class="modal-footer d-block">' +
                    '<button type="submit" class="btn btn-warning float-end">Update</button>' +
                    '<button type="button" class="btn btn-secondary float-start" data-dismiss="modal">Close</button>' +
                    '</div>' +
                    '</form>');
            } else if (action == 'create') {
                document.getElementById('ModalLabel').innerHTML = 'Add new'
                $('#modalbody').append('<form id="form" method="post"><div class="mb-3">' +
                    `{% csrf_token %}{{form.as_p}}` +
                    '</div><div class="modal-footer d-block"><button type="submit" class="btn btn-warning float-end">Add</button> ' +
                    '<button type="button" class="btn btn-secondary float-start" data-dismiss="modal">Close</button></div></form>');
                document.getElementById("id_name").classList.add("form-control");
                document.getElementById("id_url").classList.add("form-control");
            }
        })

        function del(val) {
            $.ajax({
                url: '../' + 'delete_single' + '/' + val + '/',
                success: function (data) {
                    window.location.reload();
                },
            })
        }

        function update() {
            var id = document.getElementById('data_id').innerHTML;
            var name = document.getElementById('bname').value;
            var link = document.getElementById('blink').value;
            link = encodeURIComponent(link)
            $.ajax({
                url: '../' + 'edit' + '/' + id + '/' + name + '/' + encodeURIComponent(link) + '/',
                success: function (data) {
                }
            })
            setTimeout(function () {
                document.location.reload();
            }, 100);
            window.location.reload();
        }

        $(".modal").on("hidden.bs.modal", function () {
            $(".modal-body").html("");
            document.getElementById('ModalLabel').innerHTML = ''
        })
    </script>
{% endblock body_content %}

currency_app/templates/dummy.html
{% extends template %}

currency_app/templates/index.html
{% extends 'template.html' %}
{% block body_content %}
    <div class="card text-center">
        <div class="card-body">
            <h5 class="card-title">Welcome to currency App</h5>
            <p class="card-text">Use the following menu to navigate</p>
            <a href="{% url 'currency_app:rate-list' %}" class="btn btn-primary">Rate list</a>
            <p>
            <p>
                <a href="{% url 'currency_app:bank-list' %}" class="btn btn-primary">Bank list</a>
            <p>
            <p>
                <a href="{% url 'currency_app:contact_us_list' %}" class="btn btn-primary">Messages</a>
            <p>
            <p>
                {% if request.user.is_authenticated %}
                    <p>
                    <p>
                        <a href="{% url 'logout' %}" class="btn btn-primary">Logout</a>
                    <p>
                    <p>
                        <a href="{% url 'accounts:profile' %}" class="btn btn-primary">Profile</a>
                    <p>
                    <p>
                        <a href="{% url 'accounts:change-password' %}" class="btn btn-primary">Change Password</a>
                        {% else %}
                        <a href="{% url 'login' %}" class="btn btn-primary">Login</a>
                    <p>
                    <p>
                        <a href="{% url 'accounts:signup' %}" class="btn btn-primary">Sign Up</a>
                    <p>
                    <p>
                        <a href="{% url 'password_reset' %}" class="btn btn-primary">Forgot your password?</a>
                    <p>
                    <p>
                {% endif %}

        </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="Modal" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLabel"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="modalbody">
                </div>
            </div>
        </div>
    </div>
    <!-- Contact US -->
    {#    <a class="contact" href="{% url 'currency_app:contact_us_create' %}">CONTACT US</a>#}
    {#    <script>#}
    {#        document.getElementById("home").classList.add("active");#}
    {#        document.title = "Home";#}
    {#    </script>#}
{% endblock body_content %}

currency_app/templates/template.html
{# Load the tag library #}
{% load bootstrap5 %}
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Currency App</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/bootstrap.min.css' %}"/>
    <!-- Awesome Fonts -->
    <link rel="stylesheet" type="text/css" href="{% static 'awesome/css/all.min.css' %}"/>
</head>
<style>
    @font-face {
        font-family: "QuicksandLight";
        src: url("{% static 'quicksand/QuicksandLight.eot' %}");
        src: url("{% static 'quicksand/QuicksandLight.eot?#iefix' %}") format("embedded-opentype"),
        url("{% static 'quicksand/QuicksandLight.woff' %}") format("woff"),
        url("{% static 'quicksand/QuicksandLight.ttf' %}") format("truetype");
        font-style: normal;
        font-weight: 300;
    }

    body {
        min-height: 81.4vh;
        background: linear-gradient(0deg, #fff, 50%, rgb(210, 231, 252));
        font-family: 'QuicksandLight', sans-serif;
        font-weight: bold;
        background-repeat: no-repeat;
        overflow-x: hidden;
    }

    tr td, tr th {
        background-color: rgba(255, 255, 255, 1) !important;
        text-align: center;
        margin-top: auto;
        margin-bottom: auto;
    }

    table {
        box-shadow: 0px 0px 1px 0px #6c757d;
    }

    .pic {
        border-radius: 50%;
    }

    .errorlist {
        visibility: hidden;
    }

    .contact {
        position: fixed;
        bottom: 30px;
        right: 40px;
    }

    .table td, .table th {
        min-width: 100px;
        max-width: 300px;
    }

    #outer {
        min-width: 135px;
        text-align: center;
    }

    .inner {
        display: inline-block;
    }

    .errorlist {
        visibility: visible
    }

    .content {
        padding-bottom: 40px;
        padding-top: 30px;
    }
</style>
<body>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>


<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'dollar.png' %}" width="20" height="30"
                                                          alt=""> Currency App</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            {#            <li class="nav-item active">#}
            {#                <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>#}
            {#            </li>#}
            {#            <li class="nav-item">#}
            {#                <a class="nav-link" href="#">Features</a>#}
            {#            </li>#}
            {#            <li class="nav-item">#}
            {#                <a class="nav-link" href="#">Pricing</a>#}
            {#            </li>#}
        </ul>
        <ul class="navbar-nav">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:change-password' %}">Change password</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Hi, {{ request.user.username }}!</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'password_reset' %}">Forgot your password?</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}
<div class="content">
    {% block body_content %}
    {% endblock body_content %}
</div>
</body>
<footer class=" bg-primary text-white text-center text-lg-start fixed-bottom">
    <!-- Grid container -->
    <div id="footer_body" class="container p-4">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
                {#                <h5 class="text-uppercase">Footer Content</h5>#}
                <p>
                    Currency is an application for more than 5 currencies over Ukraine with
                    live exchange rates and offline mode. Setup your account to be in touch with a real time updates
                    and see all the important ...
                </p>
            </div>
            <!--Grid column-->
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                {#                <h5 class="text-uppercase">Links</h5>#}
                <ul class="list-unstyled mb-0">
                    <li id="home" class="text-white text-uppercase">
                        <a class="text-white" href="{% url 'index' %}">Home</a>
                    </li>
                    <li id="banklist" class="text-white text-uppercase">
                        <a class="text-white" href="{% url 'currency_app:bank-list' %}">Bank list</a>
                    </li>
                    <li id="ratelist" class="text-white text-uppercase">
                        <a class="text-white" href="{% url 'currency_app:rate-list' %}">Rate list</a>
                    </li>
                    <li id="ratelist" class="text-white text-uppercase">
                        <a class="text-white" href="{% url 'currency_app:contact_us_create' %}">Contact Us</a>
                    </li>
                    <li id="ratelist" class="text-white text-uppercase">
                        <a class="text-white" href="{% url 'api.v1:schema-redoc' %}">Redoc</a>
                    </li>
                    <li id="ratelist" class="text-white text-uppercase">
                        <a class="text-white" href="{% url 'api.v1:schema-swagger-ui' %}">Swagger</a>
                    </li>

                </ul>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                <ul class="list-unstyled">
                    {% if request.user.is_authenticated %}
                        <li id="messages" class="text-white text-uppercase">
                            <a class="text-white" href="{% url 'currency_app:contact_us_list' %}">Messages</a>
                        </li>
                        <li id="admin" class="text-white text-uppercase">
                            <a class="text-white" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2021
        <a class="text-white" href="https://mdbootstrap.com/">Currency App</a>
    </div>
    <!-- Copyright -->
</footer>
</html>